# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_auto_20171222_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='VAT_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='VAT amount'),
        ),
    ]
