# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total amount')),
                ('currency', models.CharField(max_length=30, verbose_name='currency')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='base amount')),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='VAT amount')),
                ('invoice_type', models.CharField(max_length=30, verbose_name='invoice type')),
                ('invoice_date', models.DateField(verbose_name='invoice date')),
                ('invoice_category', models.CharField(max_length=30, verbose_name='invoice category')),
                ('invoice_project', models.CharField(max_length=30, verbose_name='invoice project')),
                ('comments', models.CharField(max_length=30, verbose_name='invoice comments')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'img/upload')),
            ],
        ),
    ]
