# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_auto_20171227_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[(b'notsubmitted', 'not submitted'), (b'inprogress', 'in progress'), (b'approved', 'approved')], default=b'notsubmitted', max_length=30, null=True, verbose_name='invoice status'),
        ),
    ]
