# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_auto_20171227_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbusementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(b'inprogress', 'in progress'), (b'approved', 'approved'), (b'rejected', 'rejected')], default=b'inprogress', max_length=30, null=True, verbose_name='reimbursement status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total amount')),
            ],
            options={
                'verbose_name': 'reimbusement request',
                'verbose_name_plural': 'reimbusement request',
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'invoice', 'verbose_name_plural': 'invoice'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='reimbursement_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reimbursement.ReimbusementRequest', verbose_name='reimbusement request'),
        ),
    ]
