# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0008_auto_20180102_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalchain',
            options={'verbose_name': 'approval chain', 'verbose_name_plural': 'approval chain'},
        ),
        migrations.AddField(
            model_name='reimbusementrequest',
            name='launcher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='launcher'),
            preserve_default=False,
        ),
    ]
