# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0009_auto_20180102_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbusementrequest',
            name='current_approver_chain',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reimbursement.ApprovalChain', verbose_name='current approver chain'),
            preserve_default=False,
        ),
    ]
