# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0010_reimbusementrequest_current_approver_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbusementrequest',
            name='current_approver_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reimbursement.ApprovalChain', verbose_name='current approver chain'),
        ),
    ]
