# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0011_auto_20180105_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(b'inprogress', 'in progress'), (b'approved', 'approved'), (b'rejected', 'rejected')], default=b'inprogress', max_length=30, null=True, verbose_name='reimbursement status')),
                ('comments', models.CharField(blank=True, max_length=30, null=True, verbose_name='approve comments')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='approver')),
                ('reimbursement_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reimbursement.ReimbusementRequest', verbose_name='reimbusement request')),
            ],
        ),
    ]
