# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0013_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='status',
            field=models.CharField(blank=True, choices=[(b'inprogress', '\u5904\u7406\u4e2d'), (b'approved', '\u5df2\u6279\u51c6'), (b'rejected', '\u5df2\u62d2\u7edd')], default=b'inprogress', max_length=30, null=True, verbose_name='reimbursement status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[(b'RMB', '\u4eba\u6c11\u5e01'), (b'USD', '\u7f8e\u5143'), (b'EUR', '\u6b27\u5143')], max_length=30, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_category',
            field=models.CharField(choices=[(b'1', '\u8fd0\u8425'), (b'2', '\u5e02\u573a'), (b'3', '\u7814\u53d1')], max_length=30, verbose_name='invoice category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_project',
            field=models.CharField(choices=[(b'1', '\u9910\u996e'), (b'2', '\u623f\u79df'), (b'3', '\u51fa\u5dee')], max_length=30, verbose_name='invoice project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[(b'notsubmitted', '\u672a\u63d0\u4ea4'), (b'inprogress', '\u5904\u7406\u4e2d'), (b'approved', '\u5df2\u6279\u51c6')], default=b'notsubmitted', max_length=30, null=True, verbose_name='invoice status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[(b'ordinary', '\u666e\u7968'), (b'special', '\u4e13\u7968'), (b'notinvoice', '\u975e\u53d1\u7968')], max_length=30, verbose_name='invoice type'),
        ),
        migrations.AlterField(
            model_name='reimbusementrequest',
            name='status',
            field=models.CharField(blank=True, choices=[(b'inprogress', '\u5904\u7406\u4e2d'), (b'approved', '\u5df2\u6279\u51c6'), (b'rejected', '\u5df2\u62d2\u7edd')], default=b'inprogress', max_length=30, null=True, verbose_name='reimbursement status'),
        ),
    ]
